package com.company.mapper;

import com.company.model.TGroupUser;
import com.company.model.TGroupUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int countByExample(TGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int deleteByExample(TGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int insert(TGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int insertSelective(TGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    List<TGroupUser> selectByExample(TGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    TGroupUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") TGroupUser record, @Param("example") TGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int updateByExample(@Param("record") TGroupUser record, @Param("example") TGroupUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int updateByPrimaryKeySelective(TGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_user
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int updateByPrimaryKey(TGroupUser record);
}