package com.company.mapper;

import com.company.model.TGroup;
import com.company.model.TGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int countByExample(TGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int deleteByExample(TGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int insert(TGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int insertSelective(TGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    List<TGroup> selectByExample(TGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    TGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") TGroup record, @Param("example") TGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int updateByExample(@Param("record") TGroup record, @Param("example") TGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int updateByPrimaryKeySelective(TGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    int updateByPrimaryKey(TGroup record);
}