package com.company.model;

public class TAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.passwd
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.nickname
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.phoneno
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private String phoneno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.id
     *
     * @return the value of t_admin.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.id
     *
     * @param id the value for t_admin.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.passwd
     *
     * @return the value of t_admin.passwd
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.passwd
     *
     * @param passwd the value for t_admin.passwd
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.nickname
     *
     * @return the value of t_admin.nickname
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.nickname
     *
     * @param nickname the value for t_admin.nickname
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.phoneno
     *
     * @return the value of t_admin.phoneno
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public String getPhoneno() {
        return phoneno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.phoneno
     *
     * @param phoneno the value for t_admin.phoneno
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }
}