package com.company.model;

public class TGroupRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_role.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_role.groupid
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private Long groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group_role.roleid
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private Long roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_role.id
     *
     * @return the value of t_group_role.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_role.id
     *
     * @param id the value for t_group_role.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_role.groupid
     *
     * @return the value of t_group_role.groupid
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public Long getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_role.groupid
     *
     * @param groupid the value for t_group_role.groupid
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setGroupid(Long groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group_role.roleid
     *
     * @return the value of t_group_role.roleid
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group_role.roleid
     *
     * @param roleid the value for t_group_role.roleid
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }
}