package com.company.model;

public class TGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_group.groupname
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private String groupname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group.id
     *
     * @return the value of t_group.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group.id
     *
     * @param id the value for t_group.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_group.groupname
     *
     * @return the value of t_group.groupname
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_group.groupname
     *
     * @param groupname the value for t_group.groupname
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }
}