package com.company.model;

public class TRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.descpt
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private String descpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.category
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role
     *
     * @return the value of t_role.role
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role
     *
     * @param role the value for t_role.role
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.descpt
     *
     * @return the value of t_role.descpt
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public String getDescpt() {
        return descpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.descpt
     *
     * @param descpt the value for t_role.descpt
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setDescpt(String descpt) {
        this.descpt = descpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.category
     *
     * @return the value of t_role.category
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.category
     *
     * @param category the value for t_role.category
     *
     * @mbggenerated Thu May 19 14:27:32 CST 2016
     */
    public void setCategory(String category) {
        this.category = category;
    }
}